server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: neo_route
          uri: http://www.ityouknow.com
          predicates:
            - Path=/spring
        - id: url1
          uri: http://localhost:4444
          predicates:
            - Path=/hello/**